import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.49.1";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

interface CreateProjectRequest {
  project_name: string;
  investor_id: string;
  intake_year?: number;
  // Optional fields
  status?: string;
  capacity_kwp?: number;
  feeder_code?: string;
  city?: string;
  district?: string;
  address?: string;
  coordinates?: string;
  land_owner?: string;
  land_owner_contact?: string;
  contact_person?: string;
  contact_phone?: string;
  note?: string;
  installation_type?: string;
  actual_installed_capacity?: number;
  taipower_pv_id?: string;
  grid_connection_type?: string;
  power_phase_type?: string;
  power_voltage?: string;
  pole_status?: string;
  construction_status?: string;
}

serve(async (req) => {
  // Handle CORS preflight
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    // Get authorization header
    const authHeader = req.headers.get('authorization');
    if (!authHeader) {
      console.error('No authorization header provided');
      return new Response(
        JSON.stringify({ error: '未授權' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Create Supabase client with user's token
    const supabaseUrl = Deno.env.get('SUPABASE_URL')!;
    const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
    
    const supabaseClient = createClient(supabaseUrl, supabaseServiceKey, {
      auth: {
        autoRefreshToken: false,
        persistSession: false,
      },
      global: {
        headers: { Authorization: authHeader },
      },
    });

    // Verify user
    const { data: { user }, error: authError } = await supabaseClient.auth.getUser(
      authHeader.replace('Bearer ', '')
    );
    
    if (authError || !user) {
      console.error('Auth error:', authError);
      return new Response(
        JSON.stringify({ error: '使用者驗證失敗' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('User verified:', user.id);

    // Parse request body
    const body: CreateProjectRequest = await req.json();
    console.log('Request body:', body);

    if (!body.investor_id) {
      return new Response(
        JSON.stringify({ error: '必須選擇投資方' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (!body.project_name) {
      return new Response(
        JSON.stringify({ error: '必須填寫案場名稱' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    // Get investor code
    const { data: investor, error: investorError } = await supabaseClient
      .from('investors')
      .select('investor_code')
      .eq('id', body.investor_id)
      .single();

    if (investorError || !investor) {
      console.error('Investor fetch error:', investorError);
      return new Response(
        JSON.stringify({ error: '找不到投資方資料' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    if (!investor.investor_code) {
      return new Response(
        JSON.stringify({ error: '投資方尚未設定代碼，請先在投資方資料補齊代碼' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const investorCode = investor.investor_code.toUpperCase();
    const intakeYear = body.intake_year || new Date().getFullYear();

    console.log('Getting next sequence for:', intakeYear, investorCode);

    // Use service role client for atomic counter update
    const serviceClient = createClient(supabaseUrl, supabaseServiceKey);

    // Get next sequence number atomically using the database function
    const { data: seqResult, error: seqError } = await serviceClient
      .rpc('get_next_project_seq', {
        p_year: intakeYear,
        p_investor_code: investorCode,
      });

    if (seqError) {
      console.error('Sequence generation error:', seqError);
      return new Response(
        JSON.stringify({ error: '流水號生成失敗：' + seqError.message }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    const seq = seqResult as number;
    console.log('Generated sequence:', seq);

    // Generate project_code (site_code_display will be generated by trigger)
    const projectCode = `${intakeYear}${investorCode}${String(seq).padStart(4, '0')}`;

    console.log('Generated project code:', projectCode);

    // Create project with the generated sequence
    const projectData: Record<string, unknown> = {
      project_code: projectCode,
      project_name: body.project_name,
      investor_id: body.investor_id,
      intake_year: intakeYear,
      seq: seq,
      created_by: user.id,
      status: body.status || '開發中',
    };

    // Add optional fields if provided
    if (body.capacity_kwp !== undefined) projectData.capacity_kwp = body.capacity_kwp;
    if (body.feeder_code) projectData.feeder_code = body.feeder_code;
    if (body.city) projectData.city = body.city;
    if (body.district) projectData.district = body.district;
    if (body.address) projectData.address = body.address;
    if (body.coordinates) projectData.coordinates = body.coordinates;
    if (body.land_owner) projectData.land_owner = body.land_owner;
    if (body.land_owner_contact) projectData.land_owner_contact = body.land_owner_contact;
    if (body.contact_person) projectData.contact_person = body.contact_person;
    if (body.contact_phone) projectData.contact_phone = body.contact_phone;
    if (body.note) projectData.note = body.note;
    if (body.installation_type) projectData.installation_type = body.installation_type;
    if (body.actual_installed_capacity !== undefined) projectData.actual_installed_capacity = body.actual_installed_capacity;
    if (body.taipower_pv_id) projectData.taipower_pv_id = body.taipower_pv_id;
    if (body.grid_connection_type) projectData.grid_connection_type = body.grid_connection_type;
    if (body.power_phase_type) projectData.power_phase_type = body.power_phase_type;
    if (body.power_voltage) projectData.power_voltage = body.power_voltage;
    if (body.pole_status) projectData.pole_status = body.pole_status;
    if (body.construction_status) projectData.construction_status = body.construction_status;

    // Insert using service client to bypass RLS, but with user's ID as created_by
    const { data: newProject, error: insertError } = await serviceClient
      .from('projects')
      .insert(projectData)
      .select('id, project_code, site_code_display, intake_year, seq')
      .single();

    if (insertError) {
      console.error('Project insert error:', insertError);
      
      // Handle duplicate sequence error
      if (insertError.code === '23505') {
        return new Response(
          JSON.stringify({ error: '案場編號重複，請重試' }),
          { status: 409, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
        );
      }
      
      return new Response(
        JSON.stringify({ error: '案場建立失敗：' + insertError.message }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    console.log('Project created successfully:', newProject);

    return new Response(
      JSON.stringify({
        success: true,
        project: newProject,
      }),
      { status: 200, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );

  } catch (err) {
    console.error('Unexpected error:', err);
    return new Response(
      JSON.stringify({ error: '伺服器錯誤：' + (err as Error).message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
