export { DepartmentsPanel } from './DepartmentsPanel';
export { DocumentTypePanel } from './DocumentTypePanel';
export { ProcessStagesPanel } from './ProcessStagesPanel';
export { ProgressSettingsPanel } from './ProgressSettingsPanel';
export { StageResponsibilitiesPanel } from './StageResponsibilitiesPanel';
export { SystemOptionsPanel } from './SystemOptionsPanel';
export { default as TieredPricingPanel } from './TieredPricingPanel';
export { QuotePresetsPanel } from './QuotePresetsPanel';
export { default as FitRatesPanel } from './FitRatesPanel';
export { NumberPrecisionPanel } from './NumberPrecisionPanel';
